### ISSUE TITLE
Need help with the SyncUp (non Drive) version connected

### ISSUE THREAD

**Issue by lgbrownjr** [simontb/mojio-home-assistant#6]
Am unable to connect my SyncUp (mojio) tracker using the _T-mobile US SyncUp Drive_ example config with home assistant.  I get errors from home assistant stating that login was unsuccessful, and that the device_tracker could not be setup.  Because I don't have the SyncUp Drive, is it possible that the _client_id_ and/or _client_secret_ are different, due to the difference in model?  Can you give me any guidance on how to obtain them if its likely that they are different?  Additionally, is the reference to _email_ and _password_ in the config different from the credentials that are supposed to be entered into the Syncup app on my phone?

The logs I pulled from HA, and the config that i used are below.  I appreciate any help you can give me.

Thank you!

Logs:
```
This error originated from a custom integration.

Logger: custom_components.mojio.device_tracker
Source: custom_components/mojio/device_tracker.py:39
Integration: mojio (documentation)
First occurred: 3:46:42 PM (1 occurrences)
Last logged: 3:46:42 PM

Mojio authentication failed
```
And:
```log
Logger: homeassistant.components.device_tracker
Source: components/device_tracker/legacy.py:271
Integration: Device tracker (documentation, issues)
First occurred: 3:46:43 PM (1 occurrences)
Last logged: 3:46:43 PM

Error setting up platform legacy mojio
```

Additionally, the config in my configuration.yaml:
```yaml
device_tracker:
  - platform: mojio
    domain: tmobile-us
    client_id: 86d1d812-dc08-4d38-9ff3-ff86908d97e6
    client_secret: 0a6b21ec-84df-4088-ba0c-2e05592da42b
    username: <email used with the syncup app>
    password: <password to login the app>
```
